namespace Net8ConditionalRemover.Utilities;

public static class GeneratedFileDetector
{
    private static readonly string[] GeneratedExtensions =
    [
        ".g.cs",
        ".Designer.cs",
        ".generated.cs"
    ];

    private static readonly string[] GeneratedMarkers =
    [
        "<auto-generated>",
        "<auto-generated/>",
        "// This code was generated",
        "// <autogenerated",
        "// Generated by"
    ];

    public static bool IsGeneratedFile(string path, string? content = null)
    {
        foreach (var ext in GeneratedExtensions)
        {
            if (path.EndsWith(ext, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        if (content is not null)
        {
            var header = content[..Math.Min(1024, content.Length)];
            foreach (var marker in GeneratedMarkers)
            {
                if (header.Contains(marker, StringComparison.OrdinalIgnoreCase))
                    return true;
            }
        }

        return false;
    }
}
