namespace Net8ConditionalRemover.Tests.Utilities;

using Net8ConditionalRemover.Utilities;
using Xunit;

public class GeneratedFileDetectorTests
{
    [Theory]
    [InlineData("File.g.cs", true)]
    [InlineData("File.Designer.cs", true)]
    [InlineData("File.generated.cs", true)]
    [InlineData("File.cs", false)]
    [InlineData("Generated.cs", false)]
    public void IsGeneratedFile_DetectsByExtension(string fileName, bool expected)
    {
        var result = GeneratedFileDetector.IsGeneratedFile(fileName);

        Assert.Equal(expected, result);
    }

    [Theory]
    [InlineData("// <auto-generated>\nnamespace Test;", true)]
    [InlineData("// <auto-generated/>\nnamespace Test;", true)]
    [InlineData("// Generated by XYZ tool\nnamespace Test;", true)]
    [InlineData("namespace Test;\npublic class Foo { }", false)]
    public void IsGeneratedFile_DetectsByContent(string content, bool expected)
    {
        var result = GeneratedFileDetector.IsGeneratedFile("File.cs", content);

        Assert.Equal(expected, result);
    }

    [Fact]
    public void IsGeneratedFile_ChecksFirstKBOnly()
    {
        var longContent = new string('x', 2000) + "<auto-generated>";

        var result = GeneratedFileDetector.IsGeneratedFile("File.cs", longContent);

        Assert.False(result);
    }
}
